export const INCREMENT_CANDIES = 'INCREMENTCANDIES';
export const DECREMENT_CANDIES = 'DECREMENTCANDIES';
export const INCREMENT_LOLLOPOP = 'INCREMENT_LOLLOPOP';
export const DECREMENT_LOLLOPOP = 'DECREMENT_LOLLOPOP';
export const INCREMENT_CHOCOLATE = 'INCREMENT_CHOCOLATE';
export const DECREMENT_CHOCOLATE = 'DECREMENT_CHOCOLATE';
