export const DISPLAY_FEATURE_BUTTON = 'DISPLAYFEATUREBUTTON';
export const HIDE_FEATURE_BUTTON = 'HIDEFEATUREBUTTON';
export const DISPLAY_CANDYBOX = 'DISPLAYCANDYBOX';
export const DISPLAY_CONFIG = 'DISPLAYCONFIG';
export const DISPLAY_SAVE = 'DISPLAYSAVE';
export const DISPLAY_HEALTH = 'DISPLAYHEALTH';
export const DISPLAY_MAP = 'DISPLAYMAP';
